- alias: "Christmas Tree - Turn On When Home"
  trigger:
    - platform: state
      entity_id: 
        - device_tracker.kathryn_phone
        - device_tracker.madelyn_phone
      to: 'home'
  condition:
    - condition: time
      after: '07:00:00'
      before: '22:30:00'
  action:
    - service: switch.turn_on
      target:
        entity_id: 
          - switch.upstairsfamilyroomchristmastree
          - switch.basementchristmastree