automation:
  - alias: "Vacuum Room Selection"
    trigger:
      - platform: event
        event_type: input_button.pressed
        event_data:
          entity_id: input_button.vacuum_closet
      - platform: event
        event_type: input_button.pressed
        event_data:
          entity_id: input_button.vacuum_entryway
      - platform: event
        event_type: input_button.pressed
        event_data:
          entity_id: input_button.vacuum_familyroom
      - platform: event
        event_type: input_button.pressed
        event_data:
          entity_id: input_button.vacuum_garageentry
      - platform: event
        event_type: input_button.pressed
        event_data:
          entity_id: input_button.vacuum_kitchen
      - platform: event
        event_type: input_button.pressed
        event_data:
          entity_id: input_button.vacuum_kitchentable
      - platform: event
        event_type: input_button.pressed
        event_data:
          entity_id: input_button.vacuum_laundry
      - platform: event
        event_type: input_button.pressed
        event_data:
          entity_id: input_button.vacuum_madelyn
      - platform: event
        event_type: input_button.pressed
        event_data:
          entity_id: input_button.vacuum_masterbathroom
      - platform: event
        event_type: input_button.pressed
        event_data:
          entity_id: input_button.vacuum_masterbedroom
      - platform: event
        event_type: input_button.pressed
        event_data:
          entity_id: input_button.vacuum_office
    action:
      - service: group.turn_on
        target:
          entity_id: group.vacuum_rooms
      - service: switch.turn_off
        target:
          entity_id: >
            {% set room = trigger.event.data.entity_id.split('_')[1] %}
            switch.swv_{{ room }}
      - service: vacuum.start
        target:
          entity_id: vacuum.your_vacuum_entity